spring.datasource.url=jdbc:mysql://localhost:3306/uber_admin
spring.datasource.username=root
spring.datasource.password=
mybatis.mapper-locations=classpath:mybatis/*.xml
mybatis.type-aliases-package=com.empresa.gestion.model