# =============================
# Configuración de la base de datos Relationanl Databases Service (RDS)
# =============================

spring.datasource.url=jdbc:mysql://app-mini-crm.c43i2kwqem27.us-east-1.rds.amazonaws.com:3306/uber_admin?useSSL=false&serverTimezone=UTC
#-------- solo descomentar cuando haces deploy
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =============================
# MyBatis
# =============================
mybatis.mapper-locations=classpath:mybatis/*.xml
mybatis.type-aliases-package=com.chr.gestor_cliente_ventas.model

# =============================
# Hibernate / JPA
# =============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ===============================
# Servidor
# ===============================
# Puerto dinámico para Elastic Beanstalk (por default 8080 local)
server.port=${PORT:8080}

SPRING_PROFILES_ACTIVE=prod

##### ---------   Link para el sitio Web  ---------------
##    http://app-demo-crm-env.eba-uhyi74ms.us-east-1.elastcicbeanstalk.com/login